<a href="https://colab.research.google.com/github/Shiva-kalyanaram/pytorch-tutorial-using-Iris-data/blob/main/pytorch_tutorialipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch_tutorial- Day 1

starts with installation in Google colab & explore some techniques and did one sample project in Iris data classification!! **

In [ ]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

In [ ]:
#step1 - !pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
#step2- import libraries

# import torch
# import torch.nn as nn
# import torch.nn.functional as f
# import torch.optim as optim
# from torch.utils.data import DataLoader



In [2]:
import torch

In [5]:
a = torch.tensor(2)
a

tensor(2)

In [3]:
b = torch.tensor(3)
b

tensor(3)

In [6]:
a + b

tensor(5)

In [8]:
import torch # GPU enabled cuda

a = torch.tensor(2)
b = torch.tensor(3)

# Add a + b to the variable x
x = a + b

if torch.cuda.is_available():
  x = x.cuda()
  print(x)

tensor(5, device='cuda:0')


In [13]:
ones = torch.ones(4,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
random = torch.rand(3,3)#randomly generate the numbers
random

tensor([[0.5535, 0.7670, 0.0322],
        [0.7427, 0.5632, 0.7007],
        [0.8620, 0.8287, 0.5791]])

In [ ]:
#neural network !!

#contruction
#fwd propagation
#backward propagation
#iterative optimation - here comes gradient descent - it means it iteratively update the parameters to reduce the loss function or cost function!!


**Autograds**

it pytorch package, used to calculate the derivaties.

When using CNN, we have autograds and it calculate and it will help to find the derivatives.

Grad is nothing but the gradient(update the parameters) -

In [15]:
import torch

a = torch.tensor(2.5, requires_grad= True)
print(a)

tensor(2.5000, requires_grad=True)


optimizer and Loss

takes the parameter and learning rate, along with other hyperparameter.


Loss: L1, MSE, cross entrophy

In [17]:
import torch.optim as optim

params = torch.tensor([1.0,2.0], requires_grad=True)
learning_rate = 0.001

o = optim.SGD([params], lr= learning_rate)
o

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

e**xploring pytorch using Iris data**

In [39]:
import torch
import torch.nn as nn
import torch.nn.functional as f
import torch.optim as optim
from torch.utils.data import DataLoader

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [4]:
import pandas as pd
import numpy as np

In [22]:
df=pd.read_csv('/content/Iris_Data (1).csv')
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
df['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [24]:
mappings = {
    'Iris-setosa': 0,
    'Iris-versicolor': 1,
    'Iris-virginica': 2,
}

df['species'].replace(mappings, inplace=True)

In [25]:
df['species'].value_counts()

0    50
1    50
2    50
Name: species, dtype: int64

In [35]:
X = df.drop('species', axis=1).values
y= df['species'].values

In [26]:
df['species'].values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
X_train, Y_test, X_test, Y_train = train_test_split(X, Y, test_size=0.2, random_state= 42)

In [ ]:
X_train = torch.tensor(X_train, dtype= torch.float32)
Y_test =torch.tensor(Y_test, dtype = torch.float32)
X_test = torch.tensor(X_test, dtype = torch.float32)
Y_train = torch.tensor(Y_train, dtype = torch.float32)

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define neural network model
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

input_size = X_train.shape[1]
hidden_size = 128
num_classes = len(set(y_train))

model = NeuralNet(input_size, hidden_size, num_classes)

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
num_epochs = 100
for epoch in range(num_epochs):
    inputs = torch.tensor(X_train, dtype=torch.float32)
    targets = torch.tensor(y_train, dtype=torch.long)

    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, targets)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

with torch.no_grad():
    inputs = torch.tensor(X_test, dtype=torch.float32)
    outputs = model(inputs)
    _, predicted = torch.max(outputs, 1)  # Get the predicted class indices
    correct = (predicted == torch.tensor(y_test, dtype=torch.long)).sum().item()  # Count correct predictions
    accuracy = correct / len(y_test)  # Calculate accuracy
    print(f'Test Accuracy: {accuracy:.4f}')

Epoch [10/100], Loss: 0.9450
Epoch [20/100], Loss: 0.7701
Epoch [30/100], Loss: 0.6693
Epoch [40/100], Loss: 0.6043
Epoch [50/100], Loss: 0.5585
Epoch [60/100], Loss: 0.5242
Epoch [70/100], Loss: 0.4973
Epoch [80/100], Loss: 0.4755
Epoch [90/100], Loss: 0.4573
Epoch [100/100], Loss: 0.4418
Test Accuracy: 0.9000
